version: "3.9"
services:
  warehouse:
    container_name: warehouse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=test
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/test
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
    networks:
      - warehouse
    depends_on:
      - postgres-db


  postgres-db:
    container_name: warehouse-postgres
    image: "postgres:16.3"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - warehouse

networks:
  warehouse:
    driver: bridge

volumes:
  postgres-db:
    driver: local